spring.application.name=gen_ai_model
# Desktop me decrypted property rakhi hai waha password dekh skte hai...
# JSP Path Config
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

# H2 Database Config (Easy local testing)
#spring.datasource.url=jdbc:h2:mem:vishaldb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.h2.console.enabled=true

# MySQL Real Database Config
# --------------------------------------------------
#spring.datasource.url=jdbc:mysql://localhost:3306/gen_ai_model?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.url=jdbc:mysql://localhost:3306/gen_ai_model?allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate / JPA Properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Gmail SMTP 
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=vishaldeshmukh2688@gmail.com
spring.mail.password=${MAIL_PASSWORD:YOUR_GMAIL_APP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# Gemini API Key
gemini.api.key=${GEMINI_API_KEY:YOUR_GEMINI_API_KEY}